kind: pipeline
type: docker
name: default

steps:
- name: test
  image: alpine
  commands:
  - echo hello
  - echo world
  - echo "$PWD"
  - echo "$HOSTNAME"

trigger:
  branch:
  - main
  event:
  - push