kind: pipeline
type: docker
name: test-docker

# If the platform is unspecified, it defaults to Linux amd64 anyway
platform:
  os: linux
  arch: amd64

# The default is /drone/src
workspace:
  path: /drone/my-workspace

steps:
- name: test-step
  pull: if-not-exists
  image: python:3.12.0a3-alpine3.17
  environment:
    TESTY: test-environment-variable
    VARIABLE-FROM-MY-SECRET:
      from_secret: my_secret_test
  commands:
  - echo hello
  - echo world
  - echo "$PWD"
  - echo "$HOSTNAME"
  - echo $(ls)
  - python python-file.py
  when:
    branch:
    - main
    event:
    - push