apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: samuelwalters/apptest:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  # NodePort allows access from outside the cluster.
  type: NodePort
  selector:
    app: myapp
  ports:
      # Exposes the Kubernetes service within the cluster.
    - port: 80
      # Port which the service will send requests to.
      targetPort: 80
      # NodePort range: 30000-32767.
      nodePort: 30000