apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-server
  template:
    metadata:
      labels:
        app: drone-server
    spec:
      containers:
      - name: drone-server
        image: drone/drone:2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
          - name: "DRONE_GITHUB_CLIENT_ID"
            value: value-here
          - name: "DRONE_GITHUB_CLIENT_SECRET"
            value: value-here
          - name: "DRONE_RPC_SECRET"
            value: value-here
          - name: "DRONE_SERVER_HOST"
            value: https://23a9-2-121-35-82.eu.ngrok.io
          - name: "DRONE_SERVER_PROTO"
            value: https
---
apiVersion: v1
kind: Service
metadata:
  name: drone-server-service
spec:
  type: NodePort
  selector:
    app: drone-server
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000